### ISSUE TITLE
libnx hid is deprecated and no longer supported

### ISSUE THREAD

**Issue by SundayReds** [caseif/SkyMM-NX#8]
SkyMM-NX will no longer build with newer versions of libnx due to them officially deprecating and removing all legacy hid API.

eg. types like `HidControllerKeys` will no longer be recognized

See [libnx commit 637dd12](https://github.com/switchbrew/libnx/commit/637dd12b2df58c469d4e87a48aa3ebf0bc359766)

**Comment by SundayReds** [comment]
Have made a PR to fix this. It should be safe to merge.

PR #9

**Comment by caseif** [comment]
Closed via 5674a29eabb0017c6c41267c913d493ff0af9817.
